#!/usr/bin/env python3
"""Extract Elite Plus game tables from original/ELITE.EXE into core/ep_tables.{c,h}."""
import os
import struct
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import unexepack  # noqa: E402

ROOT = os.path.join(HERE, "..", "..")
raw = unexepack.unpack(open(os.path.join(ROOT, "original", "ELITE.EXE"), "rb").read(), quiet=True)
img = raw[struct.unpack_from("<H", raw, 8)[0] * 16:]
DS = 0x0B00 * 16


def ds(off, n):
    return img[DS + off:DS + off + n]


def words(off, n):
    return list(struct.unpack_from(f"<{n}H", img, DS + off))


def code(addr, expect):
    """Check the instruction bytes at addr (segment 0000) before trusting a table address."""
    assert img[addr:addr + len(expect)] == expect, f"unexpected code at {addr:04x}"


def arr(vals, per=12, fmt="{:#06x}"):
    return ",\n    ".join(", ".join(fmt.format(v) for v in vals[i:i + per])
                          for i in range(0, len(vals), per))


# load_galaxy_seed (5e25): bx = 0x5509 + 6 * galaxy
code(0x5E34, bytes([0x81, 0xC3, 0x09, 0x55]))
galaxy_seeds = words(0x5509, 8 * 3)
# planet_name (6130): digram pairs at ds:5585, index = seed byte & 0x1f
code(0x6153, bytes([0xBB, 0x85, 0x55]))
digrams = ds(0x5585, 64)
assert b"LAVE" in digrams



def cstr(off):
    b = img[DS + off:DS + off + 256]
    return b[:b.index(0)]


def clit(b):
    """C string literal; escapes split off so a following hex digit is not swallowed."""
    out, prev_hex = '"', False
    for ch in b:
        if 0x20 <= ch < 0x7F and ch not in (0x22, 0x5C):
            if prev_hex and chr(ch) in "0123456789abcdefABCDEF":
                out += '" "'
            out += chr(ch)
            prev_hex = False
        else:
            out += f"\\x{ch:02x}"
            prev_hex = True
    return out + '"'


# describe_system (632b) expands the template ds:5a35 with the printer 6396: bytes 1..6 are
# control codes (handlers ds:5b3e), bytes >= 0x80 tokens (ds:5b4a: five alternatives each)
code(0x633C, bytes([0xBE, 0x35, 0x5A]))
code(0x63BC, bytes([0xBB, 0x4A, 0x5B]))
code(0x6431, bytes([0xBE, 0xFF, 0x63]))
template = cstr(0x5A35)
N_TOKENS = 0xA7 - 0x80
tokens = []
for t in range(N_TOKENS):
    p = words(0x5B4A + 2 * t, 1)[0]
    tokens.append([cstr(q) for q in words(p, 5)])
reach, todo = set(), [c for c in template if c >= 0x80]
while todo:
    t = todo.pop()
    if t not in reach:
        reach.add(t)
        todo += [c for o in tokens[t - 0x80] for c in o if c >= 0x80]
assert max(reach) < 0x80 + N_TOKENS
ian = cstr(0x63FF)

c = ["/* Generated by re/tools/gen_tables.py from original/ELITE.EXE. Do not edit. */",
     "/* clang-format off */", '#include "ep_tables.h"', "",
     "/* ds:5509: seed words of the eight galaxies */",
     "const uint16_t ep_galaxy_seeds[8][3] = {\n    "
     + ",\n    ".join("{ " + arr(galaxy_seeds[k:k + 3]) + " }" for k in range(0, 24, 3)) + "\n};",
     "/* ds:5585: name digrams; index 0 is two spaces (no letters) */",
     'const char ep_digrams[65] = "' + digrams.decode("ascii") + '";',
     "/* ds:5a35: system description template */",
     f"const char ep_desc_template[] = {clit(template)};",
     "/* ds:63ff: appended by text code 2 */",
     f"const char ep_desc_ian[] = {clit(ian)};",
     "/* ds:5b4a: description tokens 0x80.., five alternatives each */",
     f"const char *const ep_desc_tokens[{N_TOKENS}][5] = {{",
     ",\n".join("    { " + ", ".join(clit(o) for o in opts) + " }" for opts in tokens),
     "};", ""]
h = ["/* Generated by re/tools/gen_tables.py from original/ELITE.EXE. Do not edit. */",
     "#ifndef EP_TABLES_H", "#define EP_TABLES_H", "", "#include <stdint.h>", "",
     "extern const uint16_t ep_galaxy_seeds[8][3];", "extern const char ep_digrams[65];", "",
     f"#define EP_DESC_TOKENS {N_TOKENS}", "",
     "extern const char ep_desc_template[];", "extern const char ep_desc_ian[];",
     "extern const char *const ep_desc_tokens[EP_DESC_TOKENS][5];", "",
     "#endif", ""]
open(os.path.join(ROOT, "core", "ep_tables.c"), "w").write("\n".join(c))
open(os.path.join(ROOT, "core", "ep_tables.h"), "w").write("\n".join(h))
print("wrote core/ep_tables.c, core/ep_tables.h")
