#!/usr/bin/env python3
"""Extract Elite Plus game tables from original/ELITE.EXE into core/ep_tables.{c,h}."""
import os
import struct
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import unexepack  # noqa: E402

ROOT = os.path.join(HERE, "..", "..")
raw = unexepack.unpack(open(os.path.join(ROOT, "original", "ELITE.EXE"), "rb").read(), quiet=True)
img = raw[struct.unpack_from("<H", raw, 8)[0] * 16:]
DS = 0x0B00 * 16


def ds(off, n):
    return img[DS + off:DS + off + n]


def words(off, n):
    return list(struct.unpack_from(f"<{n}H", img, DS + off))


def code(addr, expect):
    """Check the instruction bytes at addr (segment 0000) before trusting a table address."""
    assert img[addr:addr + len(expect)] == expect, f"unexpected code at {addr:04x}"


def arr(vals, per=12, fmt="{:#06x}"):
    return ",\n    ".join(", ".join(fmt.format(v) for v in vals[i:i + per])
                          for i in range(0, len(vals), per))


# load_galaxy_seed (5e25): bx = 0x5509 + 6 * galaxy
code(0x5E34, bytes([0x81, 0xC3, 0x09, 0x55]))
galaxy_seeds = words(0x5509, 8 * 3)
# planet_name (6130): digram pairs at ds:5585, index = seed byte & 0x1f
code(0x6153, bytes([0xBB, 0x85, 0x55]))
digrams = ds(0x5585, 64)
assert b"LAVE" in digrams

c = ["/* Generated by re/tools/gen_tables.py from original/ELITE.EXE. Do not edit. */",
     "/* clang-format off */", '#include "ep_tables.h"', "",
     "/* ds:5509: seed words of the eight galaxies */",
     "const uint16_t ep_galaxy_seeds[8][3] = {\n    "
     + ",\n    ".join("{ " + arr(galaxy_seeds[k:k + 3]) + " }" for k in range(0, 24, 3)) + "\n};",
     "/* ds:5585: name digrams; index 0 is two spaces (no letters) */",
     'const char ep_digrams[65] = "' + digrams.decode("ascii") + '";', ""]
h = ["/* Generated by re/tools/gen_tables.py from original/ELITE.EXE. Do not edit. */",
     "#ifndef EP_TABLES_H", "#define EP_TABLES_H", "", "#include <stdint.h>", "",
     "extern const uint16_t ep_galaxy_seeds[8][3];", "extern const char ep_digrams[65];", "",
     "#endif", ""]
open(os.path.join(ROOT, "core", "ep_tables.c"), "w").write("\n".join(c))
open(os.path.join(ROOT, "core", "ep_tables.h"), "w").write("\n".join(h))
print("wrote core/ep_tables.c, core/ep_tables.h")
