/* Generated by re/tools/gen_tables.py from original/ELITE.EXE. Do not edit. */
#ifndef EP_TABLES_H
#define EP_TABLES_H

#include <stdint.h>

extern const uint16_t ep_galaxy_seeds[8][3];
extern const char ep_digrams[65];

#endif
