/* Generated by re/tools/gen_tables.py from original/ELITE.EXE. Do not edit. */
#ifndef EP_TABLES_H
#define EP_TABLES_H

#include <stdint.h>

extern const uint16_t ep_galaxy_seeds[8][3];
extern const char ep_digrams[65];

#define EP_DESC_TOKENS 39

extern const char ep_desc_template[];
extern const char ep_desc_ian[];
extern const char *const ep_desc_tokens[EP_DESC_TOKENS][5];

#define EP_GOODS 17

extern const char *const ep_goods_names[EP_GOODS];
extern const uint16_t ep_goods_eco_factor[EP_GOODS][8];
extern const uint16_t ep_goods_gov_factor[EP_GOODS][8];
extern const uint16_t ep_goods_base_price[EP_GOODS];
extern const int8_t ep_goods_tech_adj[EP_GOODS][3];
extern const uint16_t ep_market_rng0[3];

#define EP_EQUIPMENT 14

typedef struct {
    uint8_t min_tech;
    const char *name;
    int8_t gov_factor, eco_factor;
    uint16_t base_price;
} ep_equipment_record;

extern const ep_equipment_record ep_equipment[EP_EQUIPMENT];

extern const uint16_t ep_model_offset[32];
extern const uint8_t ep_models[9644];
extern const int16_t ep_sin1024[1024];
extern const int16_t ep_sin2048[2048];

#define EP_TITLE_SHIPS 24

extern const uint8_t ep_title_ships[EP_TITLE_SHIPS];
extern const uint16_t ep_title_min_dist[32];
extern const char *const ep_ship_names[30];

extern const uint8_t ep_mcga_colour[256];
extern const uint8_t ep_dac[768];

#define EP_COMMANDER_SIZE 226

extern const uint8_t ep_commander0[EP_COMMANDER_SIZE];

#endif
